# Generated by Django 4.2.15 on 2024-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Register_Number', models.CharField(max_length=19)),
                ('Mail_id', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
